package org.gravel.support.compiler.ast;

/*
	This file is automatically generated. See FX.TService.TService class>>generateWorkspaces
	(C) CosmoCows B.V.
*/

import java.math.BigDecimal;
import java.math.BigInteger;
import org.gravel.support.jvm.NonLocalReturn;
import org.gravel.support.compiler.ast.IntermediateNode;
import org.gravel.support.compiler.ast.IntermediateNode.IntermediateNode_Factory;
import org.gravel.support.compiler.ast.Expression;
import org.gravel.support.compiler.ast.SequenceNode;
import org.gravel.support.compiler.ast.NodeVisitor;
import org.gravel.support.compiler.ast.Node;
import org.gravel.support.compiler.ast.SourcePrinter;
import org.gravel.support.compiler.ast.SourcePosition;

abstract public class BooleanBinaryNode extends IntermediateNode implements Cloneable {

	public static BooleanBinaryNode_Factory factory = new BooleanBinaryNode_Factory();

	Expression _left;

	SequenceNode _right;

	public static class BooleanBinaryNode_Factory extends IntermediateNode_Factory {

		public BooleanBinaryNode basicNew() {
			throw new RuntimeException("BooleanBinaryNode is an abstract class");
		}

		public BooleanBinaryNode left_right_(final Expression _anUnaryMessageNode, final SequenceNode _aSequenceNode) {
			return ((BooleanBinaryNode) this.basicNew().initializeLeft_right_(_anUnaryMessageNode, _aSequenceNode));
		}
	}

	static public BooleanBinaryNode _left_right_(Object receiver, final Expression _anUnaryMessageNode, final SequenceNode _aSequenceNode) {
		return factory.left_right_(_anUnaryMessageNode, _aSequenceNode);
	}

	@Override
	public <X> X accept_(final NodeVisitor<X> _visitor) {
		return _visitor.visitBooleanBinaryNode_(this);
	}

	@Override
	public BooleanBinaryNode allNodesDo_(final org.gravel.support.jvm.Block1<Object, Node> _aBlock) {
		this.nodesDo_(new org.gravel.support.jvm.Block1<Object, Node>() {

			@Override
			public Object value_(final Node _each) {
				return _each.withAllNodesDo_(_aBlock);
			}
		});
		return this;
	}

	@Override
	public BooleanBinaryNode allNodesDo_pruneWhere_(final org.gravel.support.jvm.Block1<Object, Node> _aBlock, final org.gravel.support.jvm.Block1<Boolean, Node> _pruneBlock) {
		this.nodesDo_(new org.gravel.support.jvm.Block1<Object, Node>() {

			@Override
			public Object value_(final Node _each) {
				if (!_pruneBlock.value_(_each)) {
					return _each.withAllNodesDo_pruneWhere_(_aBlock, _pruneBlock);
				}
				return BooleanBinaryNode.this;
			}
		});
		return this;
	}

	public BooleanBinaryNode copy() {
		try {
			BooleanBinaryNode _temp1 = (BooleanBinaryNode) this.clone();
			_temp1.postCopy();
			return _temp1;
		} catch (CloneNotSupportedException e) {
			throw new RuntimeException(e);
		}
	}

	public BooleanBinaryNode_Factory factory() {
		return factory;
	}

	public BooleanBinaryNode initializeLeft_right_(final Expression _anUnaryMessageNode, final SequenceNode _aSequenceNode) {
		_left = _anUnaryMessageNode;
		_right = _aSequenceNode;
		this.initialize();
		return this;
	}

	@Override
	public abstract BooleanBinaryNode innerSourceOn_(final StringBuilder _aStream);

	public Expression left() {
		return _left;
	}

	@Override
	public BooleanBinaryNode localVarNamesDo_(final org.gravel.support.jvm.Block1<Object, String> _aBlock) {
		return this;
	}

	@Override
	public BooleanBinaryNode nodesDo_(final org.gravel.support.jvm.Block1<Object, Node> _aBlock) {
		_aBlock.value_(_left);
		_aBlock.value_(_right);
		return this;
	}

	@Override
	public BooleanBinaryNode prettySourceOn_(final StringBuilder _aStream) {
		SourcePrinter.factory.on_(_aStream).visit_(this);
		return this;
	}

	@Override
	public BooleanBinaryNode printOn_(final StringBuilder _aStream) {
		final String _title;
		_title = this.factory().toString();
		_aStream.append(org.gravel.support.jvm.CharacterExtensions.isVowel(_title.charAt(0)) ? "an " : "a ");
		_aStream.append(_title);
		_aStream.append('[');
		this.sourceOn_(_aStream);
		_aStream.append(']');
		return this;
	}

	@Override
	public BooleanBinaryNode pvtSetSourcePosition_(final SourcePosition _aSourcePosition) {
		_sourcePosition = _aSourcePosition;
		return this;
	}

	public SequenceNode right() {
		return _right;
	}

	@Override
	public BooleanBinaryNode sourceOn_(final StringBuilder _aStream) {
		this.innerSourceOn_(_aStream);
		return this;
	}

	@Override
	public BooleanBinaryNode withAllNodesDo_(final org.gravel.support.jvm.Block1<Object, Node> _aBlock) {
		_aBlock.value_(this);
		this.allNodesDo_(_aBlock);
		return this;
	}

	@Override
	public BooleanBinaryNode withAllNodesDo_pruneWhere_(final org.gravel.support.jvm.Block1<Object, Node> _aBlock, final org.gravel.support.jvm.Block1<Boolean, Node> _pruneBlock) {
		_aBlock.value_(this);
		this.allNodesDo_pruneWhere_(_aBlock, _pruneBlock);
		return this;
	}

	@Override
	public BooleanBinaryNode withSourcePosition_(final SourcePosition _aSourcePosition) {
		if (_sourcePosition == _aSourcePosition) {
			return BooleanBinaryNode.this;
		}
		return this.copy().pvtSetSourcePosition_(_aSourcePosition);
	}
}
