package org.gravel.support.compiler.ast;

/*
	This file is automatically generated. See FX.TService.TService class>>generateWorkspaces
	(C) CosmoCows B.V.
*/

import java.math.BigDecimal;
import java.math.BigInteger;
import org.gravel.support.jvm.NonLocalReturn;
import org.gravel.support.compiler.jvm.JVMDefinedObjectType;
import org.gravel.support.compiler.jvm.Invoke;
import org.gravel.support.compiler.ast.ClassMapping;
import org.gravel.support.compiler.ast.SystemMapping;
import org.gravel.support.compiler.jvm.JVMType;
import org.gravel.support.compiler.ast.AbsoluteReference;
import org.gravel.support.compiler.ast.Reference;
import org.gravel.support.compiler.jvm.JVMClass;

abstract public class SystemMappingCompilerTools extends Object implements Cloneable {

	public static SystemMappingCompilerTools_Factory factory = new SystemMappingCompilerTools_Factory();

	public static class SystemMappingCompilerTools_Factory extends org.gravel.support.jvm.SmalltalkFactory {

		public SystemMappingCompilerTools basicNew() {
			throw new RuntimeException("SystemMappingCompilerTools is an abstract class");
		}
	}

	public SystemMappingCompilerTools copy() {
		try {
			SystemMappingCompilerTools _temp1 = (SystemMappingCompilerTools) this.clone();
			_temp1.postCopy();
			return _temp1;
		} catch (CloneNotSupportedException e) {
			throw new RuntimeException(e);
		}
	}

	public abstract Invoke createInvokeInstruction_name_numArgs_(final JVMDefinedObjectType _type, final String _name, final int _numArgs);

	public abstract Object evaluateBlock0Class_(final Class _aClass);

	public SystemMappingCompilerTools_Factory factory() {
		return factory;
	}

	public abstract Class findJavaClass_(final org.gravel.core.Symbol[] _anArray);

	public SystemMappingCompilerTools initialize() {
		return this;
	}

	public abstract SystemMappingCompilerTools initializeClass_systemMapping_(final ClassMapping _aClassMapping, final SystemMapping _systemMapping);

	public abstract boolean isAssignable_from_(final Class _aClass, final Class _bClass);

	public abstract Class javaClassSuperclass();

	public abstract JVMType jvmTypeForClass_(final Class _aClass);

	public abstract SystemMappingCompilerTools linkInNamespace_systemMapping_(final ClassMapping _aClassMapping, final SystemMapping _aSystemMapping);

	public abstract java.lang.invoke.MethodHandle methodHandleAt_numArgs_in_identityClass_isStatic_(final String _aString, final int _numArgs, final Class _aJavaClass, final Class _identityClass, final boolean _aBoolean);

	public abstract SystemMappingCompilerTools methodNamesIn_do_(final Class _receiverClass, final org.gravel.support.jvm.Block1<Object, String> _aBlock);

	public abstract org.gravel.support.jvm.runtime.AlmostFinalValue newSingletonHolder_value_(final AbsoluteReference _reference, final Object _value);

	public abstract String nextExtensionPostfix();

	public abstract String nextNlrMarker();

	public SystemMappingCompilerTools postCopy() {
		return this;
	}

	public abstract String referenceAsClassName_(final Reference _aReference);

	public abstract SystemMappingCompilerTools resetCallsites();

	public abstract Class superclassOf_(final Class _aClass);

	public abstract Object valueOfSingletonHolder_(final org.gravel.support.jvm.runtime.AlmostFinalValue _holder);

	public abstract Class writeClass_(final JVMClass _aJVMClass);
}
