package st.gravel.support.compiler.ast;

/*
	This file is automatically generated from typed smalltalk source. Do not edit by hand.
	(C) AG5.com
*/

import org.junit.Test;
import static org.junit.Assert.*;

public class LiteralSendInlinerTest {

	@Test
	public void initialize() {
	}
}
