package org.gravel.support.parser;

/*
	This file is automatically generated. See FX.TService.TService class>>generateWorkspaces
	(C) CosmoCows B.V.
*/

import java.math.BigDecimal;
import java.math.BigInteger;
import org.gravel.support.jvm.NonLocalReturn;
import org.gravel.support.parser.StateAccessNode;
import org.gravel.support.parser.StateAccessNode.StateAccessNode_Factory;
import org.gravel.support.parser.Expression;
import org.gravel.support.parser.NodeVisitor;
import org.gravel.support.parser.Node;
import org.gravel.support.parser.SourcePosition;

public class FieldWriteNode extends StateAccessNode implements Cloneable {

	public static FieldWriteNode_Factory factory = new FieldWriteNode_Factory();

	String _field;

	Expression _owner;

	Expression _value;

	public static class FieldWriteNode_Factory extends StateAccessNode_Factory {

		public FieldWriteNode basicNew() {
			FieldWriteNode newInstance = new FieldWriteNode();
			newInstance.initialize();
			return newInstance;
		}

		public FieldWriteNode owner_field_value_(final Expression _anExpression, final String _aString, final Expression _aVariableNode) {
			return this.basicNew().initializeOwner_field_value_(_anExpression, _aString, _aVariableNode);
		}
	}

	static public FieldWriteNode _owner_field_value_(Object receiver, final Expression _anExpression, final String _aString, final Expression _aVariableNode) {
		return factory.owner_field_value_(_anExpression, _aString, _aVariableNode);
	}

	@Override
	public <X> X accept_(final NodeVisitor<X> _visitor) {
		return _visitor.visitFieldWriteNode_(this);
	}

	@Override
	public FieldWriteNode allNodesDo_(final org.gravel.support.jvm.Block1<Object, Node> _aBlock) {
		this.nodesDo_(new org.gravel.support.jvm.Block1<Object, Node>() {

			@Override
			public Object value_(final Node _each) {
				return _each.withAllNodesDo_(_aBlock);
			}
		});
		return this;
	}

	@Override
	public FieldWriteNode allNodesDo_pruneWhere_(final org.gravel.support.jvm.Block1<Object, Node> _aBlock, final org.gravel.support.jvm.Block1<Boolean, Node> _pruneBlock) {
		this.nodesDo_(new org.gravel.support.jvm.Block1<Object, Node>() {

			@Override
			public Object value_(final Node _each) {
				if (!_pruneBlock.value_(_each)) {
					return _each.withAllNodesDo_pruneWhere_(_aBlock, _pruneBlock);
				}
				return FieldWriteNode.this;
			}
		});
		return this;
	}

	public FieldWriteNode copy() {
		try {
			FieldWriteNode _temp1 = (FieldWriteNode) this.clone();
			_temp1.postCopy();
			return _temp1;
		} catch (CloneNotSupportedException e) {
			throw new RuntimeException(e);
		}
	}

	public FieldWriteNode_Factory factory() {
		return factory;
	}

	public String field() {
		return _field;
	}

	public FieldWriteNode initializeOwner_field_value_(final Expression _anExpression, final String _aString, final Expression _aVariableNode) {
		_owner = _anExpression;
		_field = _aString;
		_value = _aVariableNode;
		this.initialize();
		return this;
	}

	@Override
	public FieldWriteNode innerSourceOn_(final StringBuilder _aStream) {
		_aStream.append("{");
		_owner.sourceOn_(_aStream);
		_aStream.append(".");
		_aStream.append(_field);
		_aStream.append(" := ");
		_value.sourceOn_(_aStream);
		_aStream.append("}");
		return this;
	}

	@Override
	public FieldWriteNode localVarNamesDo_(final org.gravel.support.jvm.Block1<Object, String> _aBlock) {
		return this;
	}

	@Override
	public String name() {
		return _field;
	}

	@Override
	public FieldWriteNode nodesDo_(final org.gravel.support.jvm.Block1<Object, Node> _aBlock) {
		_aBlock.value_(_owner);
		_aBlock.value_(_value);
		return this;
	}

	public Expression owner() {
		return _owner;
	}

	@Override
	public FieldWriteNode prettySourceOn_(final StringBuilder _aStream) {
		SourcePrinter.factory.on_(_aStream).visit_(this);
		return this;
	}

	@Override
	public FieldWriteNode printOn_(final StringBuilder _aStream) {
		final String _title;
		_title = this.factory().toString();
		_aStream.append(org.gravel.support.jvm.CharacterExtensions.isVowel(_title.charAt(0)) ? "an " : "a ");
		_aStream.append(_title);
		_aStream.append('[');
		this.sourceOn_(_aStream);
		_aStream.append(']');
		return this;
	}

	@Override
	public FieldWriteNode pvtSetSourcePosition_(final SourcePosition _aSourcePosition) {
		_sourcePosition = _aSourcePosition;
		return this;
	}

	@Override
	public boolean referencesVariable_(final String _aString) {
		return org.gravel.support.jvm.StringExtensions.equals_(_field, _aString);
	}

	@Override
	public FieldWriteNode sourceOn_(final StringBuilder _aStream) {
		this.innerSourceOn_(_aStream);
		return this;
	}

	@Override
	public Expression unoptimized() {
		return AssignmentNode.factory.variable_value_(VariableNode.factory.name_(this.name()), _value);
	}

	public Expression value() {
		return _value;
	}

	@Override
	public FieldWriteNode withAllNodesDo_(final org.gravel.support.jvm.Block1<Object, Node> _aBlock) {
		_aBlock.value_(this);
		this.allNodesDo_(_aBlock);
		return this;
	}

	@Override
	public FieldWriteNode withAllNodesDo_pruneWhere_(final org.gravel.support.jvm.Block1<Object, Node> _aBlock, final org.gravel.support.jvm.Block1<Boolean, Node> _pruneBlock) {
		_aBlock.value_(this);
		this.allNodesDo_pruneWhere_(_aBlock, _pruneBlock);
		return this;
	}

	@Override
	public FieldWriteNode withSourcePosition_(final SourcePosition _aSourcePosition) {
		if (_sourcePosition == _aSourcePosition) {
			return FieldWriteNode.this;
		}
		return this.copy().pvtSetSourcePosition_(_aSourcePosition);
	}
}
