package org.gravel.support.parser;

/*
	This file is automatically generated. See FX.TService.TService class>>generateWorkspaces
	(C) CosmoCows B.V.
*/

import java.math.BigDecimal;
import java.math.BigInteger;
import org.gravel.support.jvm.NonLocalReturn;
import org.gravel.support.parser.InstVarMapping;
import org.gravel.support.parser.InstVarMapping.InstVarMapping_Factory;

public class FieldInstVarMapping extends InstVarMapping implements Cloneable {

	public static FieldInstVarMapping_Factory factory = new FieldInstVarMapping_Factory();

	public static class FieldInstVarMapping_Factory extends InstVarMapping_Factory {

		public FieldInstVarMapping basicNew() {
			FieldInstVarMapping newInstance = new FieldInstVarMapping();
			newInstance.initialize();
			return newInstance;
		}
	}

	public FieldInstVarMapping copy() {
		try {
			FieldInstVarMapping _temp1 = (FieldInstVarMapping) this.clone();
			_temp1.postCopy();
			return _temp1;
		} catch (CloneNotSupportedException e) {
			throw new RuntimeException(e);
		}
	}

	public FieldInstVarMapping_Factory factory() {
		return factory;
	}
}
