package org.gravel.support.parser;

/*
	This file is automatically generated. See FX.TService.TService class>>generateWorkspaces
	(C) CosmoCows B.V.
*/

import java.math.BigDecimal;
import java.math.BigInteger;
import org.gravel.support.jvm.NonLocalReturn;
import org.gravel.support.parser.Reference;

public class SingletonHolder extends Object implements Cloneable {

	public static SingletonHolder_Factory factory = new SingletonHolder_Factory();

	Reference _reference;

	java.lang.invoke.SwitchPoint _switchPoint;

	Object _value;

	public static class SingletonHolder_Factory extends org.gravel.support.jvm.SmalltalkFactory {

		public SingletonHolder basicNew() {
			SingletonHolder newInstance = new SingletonHolder();
			newInstance.initialize();
			return newInstance;
		}

		public SingletonHolder reference_value_(final Reference _reference, final Object _anObject) {
			return ((SingletonHolder) this.basicNew().initializeReference_value_(_reference, _anObject));
		}
	}

	static public SingletonHolder _reference_value_(Object receiver, final Reference _reference, final Object _anObject) {
		return factory.reference_value_(_reference, _anObject);
	}

	public SingletonHolder copy() {
		try {
			SingletonHolder _temp1 = (SingletonHolder) this.clone();
			_temp1.postCopy();
			return _temp1;
		} catch (CloneNotSupportedException e) {
			throw new RuntimeException(e);
		}
	}

	public SingletonHolder_Factory factory() {
		return factory;
	}

	public SingletonHolder initialize() {
		return this;
	}

	public SingletonHolder initializeReference_value_(final Reference _aReference, final Object _anObject) {
		_reference = _aReference;
		_value = _anObject;
		this.initialize();
		return this;
	}

	public SingletonHolder postCopy() {
		return this;
	}

	public java.lang.invoke.SwitchPoint switchPoint() {
		return _switchPoint;
	}

	public SingletonHolder switchPoint_(final java.lang.invoke.SwitchPoint _anObject) {
		_switchPoint = _anObject;
		return this;
	}

	public Object value() {
		return _value;
	}

	public Object value_(final Object _anObject) {
		_value = _anObject;
		return _anObject;
	}
}
