package org.gravel.support.compiler.jvm;

/*
	This file is automatically generated. See FX.TService.TService class>>generateWorkspaces
	(C) CosmoCows B.V.
*/

import java.math.BigDecimal;
import java.math.BigInteger;
import org.gravel.support.jvm.NonLocalReturn;
import org.gravel.support.compiler.jvm.CastTo;
import org.gravel.support.compiler.jvm.CastTo.CastTo_Factory;
import org.gravel.support.compiler.jvm.JVMInstructionVisitor;
import org.gravel.support.compiler.jvm.JVMStack;
import org.gravel.support.compiler.jvm.JVMInstruction;
import org.gravel.support.compiler.jvm.JVMType;
import org.gravel.support.compiler.jvm.JVMDynamicObjectType;

public class CastIntToObject extends CastTo implements Cloneable {

	public static CastIntToObject_Factory factory = new CastIntToObject_Factory();

	public static class CastIntToObject_Factory extends CastTo_Factory {

		public CastIntToObject basicNew() {
			CastIntToObject newInstance = new CastIntToObject();
			newInstance.initialize();
			return newInstance;
		}
	}

	@Override
	public <X> X accept_(final JVMInstructionVisitor<X> _visitor) {
		return _visitor.visitCastIntToObject_(this);
	}

	public CastIntToObject copy() {
		try {
			CastIntToObject _temp1 = (CastIntToObject) this.clone();
			_temp1.postCopy();
			return _temp1;
		} catch (CloneNotSupportedException e) {
			throw new RuntimeException(e);
		}
	}

	@Override
	public JVMInstruction effectStack_(final JVMStack _aJVMStack) {
		org.gravel.support.jvm.ObjectExtensions.assert_(this, _aJVMStack.pop().isIntType());
		_aJVMStack.push_(this.type());
		return this;
	}

	public CastIntToObject_Factory factory() {
		return factory;
	}

	@Override
	public CastIntToObject printOn_(final StringBuilder _aStream) {
		final String _title;
		_title = this.factory().toString();
		_aStream.append(org.gravel.support.jvm.CharacterExtensions.isVowel(_title.charAt(0)) ? "an " : "a ");
		_aStream.append(_title);
		_aStream.append('[');
		this.sourceOn_(_aStream);
		_aStream.append(']');
		return this;
	}

	@Override
	public CastIntToObject sourceOn_(final StringBuilder _aStream) {
		return this;
	}

	@Override
	public JVMType type() {
		return JVMDynamicObjectType.factory.basicNew();
	}

	@Override
	public CastIntToObject withReturnType_(final JVMType _aType) {
		if (org.gravel.support.jvm.ObjectExtensions.equals_(this.type(), _aType)) {
			return CastIntToObject.this;
		}
		throw new RuntimeException("niy");
	}
}
