package org.gravel.support.compiler.jvm;

/*
	This file is automatically generated. See FX.TService.TService class>>generateWorkspaces
	(C) CosmoCows B.V.
*/

import java.math.BigDecimal;
import java.math.BigInteger;
import org.gravel.support.jvm.NonLocalReturn;
import org.gravel.support.compiler.jvm.JVMType;

public class JVMStack extends Object implements Cloneable {

	public static JVMStack_Factory factory = new JVMStack_Factory();

	JVMType[] _elements;

	public static class JVMStack_Factory extends org.gravel.support.jvm.SmalltalkFactory {

		public JVMStack basicNew() {
			JVMStack newInstance = new JVMStack();
			newInstance.initialize();
			return newInstance;
		}
	}

	public JVMStack copy() {
		try {
			JVMStack _temp1 = (JVMStack) this.clone();
			_temp1.postCopy();
			return _temp1;
		} catch (CloneNotSupportedException e) {
			throw new RuntimeException(e);
		}
	}

	public JVMStack elementsDo_(final org.gravel.support.jvm.Block1<Object, JVMType> _aBlock) {
		for (final JVMType _temp1 : _elements) {
			_aBlock.value_(_temp1);
		}
		return this;
	}

	public JVMStack_Factory factory() {
		return factory;
	}

	public JVMStack initialize() {
		_elements = new JVMType[] {};
		return this;
	}

	public boolean isEmpty() {
		return _elements.length == 0;
	}

	public JVMType peek() {
		return this.peek_(1);
	}

	public JVMType peek_(final int _anInteger) {
		return _elements[(_elements.length - (_anInteger - 1)) - 1];
	}

	public JVMType pop() {
		final JVMType _last;
		_last = _elements[_elements.length - 1];
		_elements = org.gravel.support.jvm.ArrayExtensions.copyWithoutLast(_elements);
		return _last;
	}

	public JVMType popLast() {
		org.gravel.support.jvm.ObjectExtensions.assert_(this, org.gravel.support.jvm.IntegerExtensions.equals_(this.size(), 1));
		return this.pop();
	}

	public JVMStack postCopy() {
		return this;
	}

	public JVMStack push_(final JVMType _aType) {
		org.gravel.support.jvm.ObjectExtensions.deny_(this, _aType.isBottomType());
		_elements = org.gravel.support.jvm.ArrayExtensions.copyWith_(_elements, _aType);
		return this;
	}

	public int size() {
		return _elements.length;
	}
}
