package org.gravel.support.compiler.jvm;

/*
	This file is automatically generated. See FX.TService.TService class>>generateWorkspaces
	(C) CosmoCows B.V.
*/

import java.math.BigDecimal;
import java.math.BigInteger;
import org.gravel.support.jvm.NonLocalReturn;
import org.gravel.support.compiler.jvm.PushConstant;
import org.gravel.support.compiler.jvm.PushConstant.PushConstant_Factory;
import org.gravel.support.compiler.jvm.JVMInstructionVisitor;
import org.gravel.support.compiler.jvm.JVMType;
import org.gravel.support.compiler.jvm.JVMDefinedObjectType;

public class PushString extends PushConstant implements Cloneable {

	public static PushString_Factory factory = new PushString_Factory();

	String _value;

	public static class PushString_Factory extends PushConstant_Factory {

		public PushString basicNew() {
			PushString newInstance = new PushString();
			newInstance.initialize();
			return newInstance;
		}

		public PushString value_(final String _aString) {
			return this.basicNew().initializeValue_(_aString);
		}
	}

	static public PushString _value_(Object receiver, final String _aString) {
		return factory.value_(_aString);
	}

	@Override
	public <X> X accept_(final JVMInstructionVisitor<X> _visitor) {
		return _visitor.visitPushString_(this);
	}

	public PushString copy() {
		try {
			PushString _temp1 = (PushString) this.clone();
			_temp1.postCopy();
			return _temp1;
		} catch (CloneNotSupportedException e) {
			throw new RuntimeException(e);
		}
	}

	public PushString_Factory factory() {
		return factory;
	}

	public PushString initializeValue_(final String _aString) {
		_value = _aString;
		this.initialize();
		return this;
	}

	@Override
	public PushString printOn_(final StringBuilder _aStream) {
		final String _title;
		_title = this.factory().toString();
		_aStream.append(org.gravel.support.jvm.CharacterExtensions.isVowel(_title.charAt(0)) ? "an " : "a ");
		_aStream.append(_title);
		_aStream.append('[');
		this.sourceOn_(_aStream);
		_aStream.append(']');
		return this;
	}

	@Override
	public PushString sourceOn_(final StringBuilder _aStream) {
		return this;
	}

	@Override
	public JVMType type() {
		return JVMDefinedObjectType.factory.string();
	}

	public String value() {
		return _value;
	}

	@Override
	public PushString withReturnType_(final JVMType _aType) {
		if (org.gravel.support.jvm.ObjectExtensions.equals_(this.type(), _aType)) {
			return PushString.this;
		}
		throw new RuntimeException("niy");
	}
}
