package org.gravel.support.compiler.jvm;

/*
	This file is automatically generated from typed smalltalk source. Do not edit by hand.
	(C) AG5.com
*/

import java.math.BigDecimal;
import java.math.BigInteger;
import org.gravel.support.jvm.NonLocalReturn;
import org.gravel.support.compiler.jvm.JVMInstruction;
import org.gravel.support.compiler.jvm.JVMInstruction.JVMInstruction_Factory;
import org.gravel.support.compiler.jvm.JVMInstructionVisitor;
import org.gravel.support.compiler.jvm.JVMStack;
import org.gravel.support.compiler.jvm.JVMType;

public class Subtract extends JVMInstruction implements Cloneable {

	public static Subtract_Factory factory = new Subtract_Factory();

	public static class Subtract_Factory extends JVMInstruction_Factory {

		public Subtract basicNew() {
			Subtract newInstance = new Subtract();
			newInstance.initialize();
			return newInstance;
		}
	}

	@Override
	public <X> X accept_(final JVMInstructionVisitor<X> _visitor) {
		return _visitor.visitSubtract_(this);
	}

	public Subtract copy() {
		try {
			Subtract _temp1 = (Subtract) this.clone();
			_temp1.postCopy();
			return _temp1;
		} catch (CloneNotSupportedException e) {
			throw new RuntimeException(e);
		}
	}

	@Override
	public JVMInstruction effectStack_(final JVMStack _aJVMStack) {
		org.gravel.support.jvm.ObjectExtensions.assert_(this, _aJVMStack.pop().isIntType());
		return this;
	}

	public Subtract_Factory factory() {
		return factory;
	}

	@Override
	public Subtract printOn_(final StringBuilder _aStream) {
		final String _title;
		_title = this.factory().toString();
		_aStream.append(org.gravel.support.jvm.CharacterExtensions.isVowel(_title.charAt(0)) ? "an " : "a ");
		_aStream.append(_title);
		_aStream.append('[');
		this.sourceOn_(_aStream);
		_aStream.append(']');
		return this;
	}

	@Override
	public Subtract sourceOn_(final StringBuilder _aStream) {
		return this;
	}

	@Override
	public Subtract withReturnType_(final JVMType _aType) {
		if (org.gravel.support.jvm.ObjectExtensions.equals_(this.type(), _aType)) {
			return Subtract.this;
		}
		throw new RuntimeException("niy");
	}
}
