package org.gravel.support.compiler.jvm;

/*
	This file is automatically generated from typed smalltalk source. Do not edit by hand.
	(C) AG5.com
*/

import java.math.BigDecimal;
import java.math.BigInteger;
import org.gravel.support.jvm.NonLocalReturn;
import org.gravel.support.compiler.jvm.JVMControlFlowInstruction;
import org.gravel.support.compiler.jvm.JVMControlFlowInstruction.JVMControlFlowInstruction_Factory;
import org.gravel.support.compiler.jvm.Frame;
import org.gravel.support.compiler.jvm.JVMDefinedObjectType;
import org.gravel.support.compiler.jvm.JVMInstructionVisitor;
import org.gravel.support.compiler.jvm.JVMStack;
import org.gravel.support.compiler.jvm.JVMInstruction;
import org.gravel.support.compiler.jvm.JVMType;

public class TryCatch extends JVMControlFlowInstruction implements Cloneable {

	public static TryCatch_Factory factory = new TryCatch_Factory();

	Frame _catchFrame;

	JVMDefinedObjectType _exception;

	Frame _tryFrame;

	public static class TryCatch_Factory extends JVMControlFlowInstruction_Factory {

		public TryCatch basicNew() {
			TryCatch newInstance = new TryCatch();
			newInstance.initialize();
			return newInstance;
		}

		public TryCatch tryFrame_exception_catchFrame_(final Frame _aFrame, final JVMDefinedObjectType _aJVMDefinedObjectType, final Frame _aFrame2) {
			return this.basicNew().initializeTryFrame_exception_catchFrame_(_aFrame, _aJVMDefinedObjectType, _aFrame2);
		}
	}

	static public TryCatch _tryFrame_exception_catchFrame_(Object receiver, final Frame _aFrame, final JVMDefinedObjectType _aJVMDefinedObjectType, final Frame _aFrame2) {
		return factory.tryFrame_exception_catchFrame_(_aFrame, _aJVMDefinedObjectType, _aFrame2);
	}

	@Override
	public <X> X accept_(final JVMInstructionVisitor<X> _visitor) {
		return _visitor.visitTryCatch_(this);
	}

	public Frame catchFrame() {
		return _catchFrame;
	}

	public TryCatch copy() {
		try {
			TryCatch _temp1 = (TryCatch) this.clone();
			_temp1.postCopy();
			return _temp1;
		} catch (CloneNotSupportedException e) {
			throw new RuntimeException(e);
		}
	}

	@Override
	public JVMInstruction effectStack_(final JVMStack _aJVMStack) {
		return this;
	}

	public JVMDefinedObjectType exception() {
		return _exception;
	}

	public TryCatch_Factory factory() {
		return factory;
	}

	public TryCatch initializeTryFrame_exception_catchFrame_(final Frame _aFrame, final JVMDefinedObjectType _aJVMDefinedObjectType, final Frame _aFrame2) {
		_tryFrame = _aFrame;
		_exception = _aJVMDefinedObjectType;
		_catchFrame = _aFrame2;
		this.initialize();
		return this;
	}

	@Override
	public TryCatch printOn_(final StringBuilder _aStream) {
		final String _title;
		_title = this.factory().toString();
		_aStream.append(org.gravel.support.jvm.CharacterExtensions.isVowel(_title.charAt(0)) ? "an " : "a ");
		_aStream.append(_title);
		_aStream.append('[');
		this.sourceOn_(_aStream);
		_aStream.append(']');
		return this;
	}

	@Override
	public TryCatch sourceOn_(final StringBuilder _aStream) {
		return this;
	}

	public Frame tryFrame() {
		return _tryFrame;
	}

	@Override
	public TryCatch withReturnType_(final JVMType _aType) {
		if (org.gravel.support.jvm.ObjectExtensions.equals_(this.type(), _aType)) {
			return TryCatch.this;
		}
		throw new RuntimeException("niy");
	}
}
