(reader extendClass: 'Integer')
!
(reader addMethod: 'durations')
!
days
	^Duration days: self
!
(reader addMethod: 'durations')
!
hours
	^Duration hours: self
!
(reader addMethod: 'durations')
!
microSeconds
	^Duration microSeconds: self
!
(reader addMethod: 'durations')
!
microseconds
	^self microSeconds
!
(reader addMethod: 'durations')
!
milliSeconds
	^Duration milliSeconds: self
!
(reader addMethod: 'durations')
!
minutes
	^Duration minutes: self
!
(reader addMethod: 'durations')
!
nanoSeconds
	^Duration nanoSeconds: self
!
(reader addMethod: 'durations')
!
seconds
	^Duration seconds: self
!
(reader addMethod: 'durations')
!
weeks
	^Duration weeks: self
!
