package org.gravel.support.compiler.ast;

/*
	This file is automatically generated. See FX.TService.TService class>>generateWorkspaces
	(C) CosmoCows B.V.
*/

import org.junit.Test;
import static org.junit.Assert.*;

public class LiteralSendInlinerTest {

	@Test
	public void initialize() {
	}
}
