package org.gravel.support.compiler.ast;

/*
	This file is automatically generated from typed smalltalk source. Do not edit by hand.
	(C) AG5.com
*/

import org.junit.Test;
import static org.junit.Assert.*;
import org.gravel.support.compiler.ast.Statement;
import org.gravel.support.compiler.ast.Parser;
import org.gravel.support.compiler.ast.AssignmentNode;
import org.gravel.support.compiler.ast.BlockNode;
import org.gravel.support.compiler.ast.BinaryMessageNode;
import org.gravel.support.compiler.ast.BinaryMethodNode;
import org.gravel.support.compiler.ast.ByteArrayLiteralNode;
import org.gravel.support.compiler.ast.CascadeNode;
import org.gravel.support.compiler.ast.CharacterLiteralNode;
import org.gravel.support.compiler.ast.FixedPointLiteralNode;
import org.gravel.support.compiler.ast.IntegerLiteralNode;
import org.gravel.support.compiler.ast.KeywordMessageNode;
import org.gravel.support.compiler.ast.KeywordMethodNode;
import org.gravel.support.compiler.ast.ArrayLiteralNode;
import org.gravel.support.compiler.ast.NamespacedVariableNode;
import org.gravel.support.compiler.ast.StringLiteralNode;
import org.gravel.support.compiler.ast.SymbolLiteralNode;
import org.gravel.support.compiler.ast.UnaryMessageNode;
import org.gravel.support.compiler.ast.UnaryMethodNode;
import org.gravel.support.compiler.ast.VariableNode;

public class ParserTest {

	@Test
	public void initialize() {
	}

	@Test
	public void testAssignmentExpression() {
		final Statement _node;
		_node = Parser.factory.source_(" foo := 7 ").parseStatement();
		assertTrue(org.gravel.support.jvm.ObjectExtensions.equals_(_node.factory(), AssignmentNode.factory));
		assertEquals((String) "foo := 7", (String) _node.prettySourceString());
	}

	@Test
	public void testAssignmentExpressionInBlock() {
		final Statement _node;
		_node = Parser.factory.source_("[ foo := 7 ]").parseStatement();
		assertTrue(org.gravel.support.jvm.ObjectExtensions.equals_(_node.factory(), BlockNode.factory));
		assertEquals((String) "[foo := 7]", (String) _node.prettySourceString());
	}

	@Test
	public void testParse2ArgBlockEmpty1() {
		final BlockNode _node;
		_node = ((BlockNode) Parser.factory.source_("[:a :b  | ]").parseExpression());
		assertTrue(org.gravel.support.jvm.ObjectExtensions.equals_(_node.factory(), BlockNode.factory));
		assertEquals((String) "[:a :b | ]", (String) _node.prettySourceString());
	}

	@Test
	public void testParse2ArgBlockEmpty2() {
		final Statement _node;
		_node = Parser.factory.source_("[:a :b ]").parseExpression();
		assertTrue(org.gravel.support.jvm.ObjectExtensions.equals_(_node.factory(), BlockNode.factory));
		assertEquals((String) "[:a :b | ]", (String) _node.prettySourceString());
	}

	@Test
	public void testParse2ArgBlockNoTemps() {
		final Statement _node;
		_node = Parser.factory.source_("[:a :b  | a foo. b bar]").parseExpression();
		assertTrue(org.gravel.support.jvm.ObjectExtensions.equals_(_node.factory(), BlockNode.factory));
		assertEquals((String) "\n[:a :b | \na foo.\nb bar]", (String) _node.prettySourceString());
	}

	@Test
	public void testParse2ArgBlockNoTempsDotEnd() {
		final Statement _node;
		_node = Parser.factory.source_("[:a :b  | a foo. b bar.]").parseExpression();
		assertTrue(org.gravel.support.jvm.ObjectExtensions.equals_(_node.factory(), BlockNode.factory));
		assertEquals((String) "\n[:a :b | \na foo.\nb bar]", (String) _node.prettySourceString());
	}

	@Test
	public void testParse2ArgBlockWithTemps() {
		final Statement _node;
		_node = Parser.factory.source_("[:a :b  | | c | a foo. b bar. c foo]").parseExpression();
		assertTrue(org.gravel.support.jvm.ObjectExtensions.equals_(_node.factory(), BlockNode.factory));
		assertEquals((String) "\n[:a :b | \n| c |\na foo.\nb bar.\nc foo]", (String) _node.prettySourceString());
	}

	@Test
	public void testParseBinaryExpression() {
		final Statement _node;
		_node = Parser.factory.source_(" 3 + 7 ").parseExpression();
		assertTrue(org.gravel.support.jvm.ObjectExtensions.equals_(_node.factory(), BinaryMessageNode.factory));
		assertEquals((String) "3 + 7", (String) _node.prettySourceString());
	}

	@Test
	public void testParseBinaryMethod() {
		final BinaryMethodNode _node;
		_node = ((BinaryMethodNode) Parser.factory.parseMethod_("+ arg ^bar"));
		assertTrue(org.gravel.support.jvm.ObjectExtensions.equals_(_node.factory(), BinaryMethodNode.factory));
		assertEquals((String) "+ arg\n\t^bar", (String) _node.prettySourceString());
	}

	@Test
	public void testParseBinaryUnaryExpression() {
		final Statement _node;
		_node = Parser.factory.source_(" 3 bar + 2 + 1 foo").parseExpression();
		assertTrue(org.gravel.support.jvm.ObjectExtensions.equals_(_node.factory(), BinaryMessageNode.factory));
		assertEquals((String) "3 bar + 2 + 1 foo", (String) _node.prettySourceString());
	}

	@Test
	public void testParseByteArray() {
		final ByteArrayLiteralNode _node;
		_node = ((ByteArrayLiteralNode) Parser.factory.source_("#[1 2 3]").parseExpression());
		assertTrue(org.gravel.support.jvm.ObjectExtensions.equals_(_node.factory(), ByteArrayLiteralNode.factory));
		assertEquals((String) "#[1 2 3]", (String) _node.prettySourceString());
		assertTrue(org.gravel.support.jvm.ByteArrayExtensions.equals_(_node.value(), new byte[] { 1, 2, 3 }));
	}

	@Test
	public void testParseByteArrayHighValues() {
		final ByteArrayLiteralNode _node;
		_node = ((ByteArrayLiteralNode) Parser.factory.source_("#[0 127 128 129 255 0]").parseExpression());
		assertTrue(org.gravel.support.jvm.ObjectExtensions.equals_(_node.factory(), ByteArrayLiteralNode.factory));
		assertEquals((String) "#[0 127 128 129 255 0]", (String) _node.prettySourceString());
		assertTrue(org.gravel.support.jvm.ByteArrayExtensions.equals_(_node.value(), new byte[] { 0, 127, -128, -127, -1, 0 }));
	}

	@Test
	public void testParseCascade() {
		final Statement _node;
		_node = Parser.factory.source_("3 foo + 2\n\t\t+ 3;\n\t\tbar: 2;\n\t\tbaz: 3;\n\t\tbaz: 4;\n\t\tboo").parseExpression();
		assertEquals((org.gravel.support.jvm.SmalltalkFactory) CascadeNode.factory, (org.gravel.support.jvm.SmalltalkFactory) _node.factory());
		assertEquals((String) "(3 foo + 2) + 3; bar: 2; baz: 3; baz: 4; boo", (String) _node.prettySourceString());
	}

	@Test
	public void testParseChar() {
		final CharacterLiteralNode _node;
		_node = ((CharacterLiteralNode) Parser.factory.source_("$a").parseExpression());
		assertTrue(org.gravel.support.jvm.ObjectExtensions.equals_(_node.factory(), CharacterLiteralNode.factory));
		assertEquals((String) "$a", (String) _node.prettySourceString());
		assertTrue(org.gravel.support.jvm.CharacterExtensions.equals_(_node.value(), 'a'));
	}

	@Test
	public void testParseEmptyBlock() {
		final Statement _node;
		_node = Parser.factory.source_("[]").parseExpression();
		assertTrue(org.gravel.support.jvm.ObjectExtensions.equals_(_node.factory(), BlockNode.factory));
		assertEquals((String) "[]", (String) _node.prettySourceString());
	}

	@Test
	public void testParseFixedPoint() {
		final FixedPointLiteralNode _node;
		_node = ((FixedPointLiteralNode) Parser.factory.source_("12345.0067s").parseExpression());
		assertEquals((org.gravel.support.jvm.SmalltalkFactory) FixedPointLiteralNode.factory, (org.gravel.support.jvm.SmalltalkFactory) _node.factory());
		assertEquals((java.math.BigDecimal) org.gravel.support.jvm.FixedPointExtensions.fromSmalltalkString_("12345.0067s"), (java.math.BigDecimal) _node.value());
	}

	@Test
	public void testParseHexInteger() {
		final IntegerLiteralNode _node;
		_node = ((IntegerLiteralNode) Parser.factory.source_("16rFF").parseExpression());
		assertEquals((org.gravel.support.jvm.SmalltalkFactory) IntegerLiteralNode.factory, (org.gravel.support.jvm.SmalltalkFactory) _node.factory());
		assertEquals(255, (int) _node.value());
	}

	@Test
	public void testParseInteger() {
		final IntegerLiteralNode _node;
		_node = ((IntegerLiteralNode) Parser.factory.source_("123").parseExpression());
		assertEquals((org.gravel.support.jvm.SmalltalkFactory) IntegerLiteralNode.factory, (org.gravel.support.jvm.SmalltalkFactory) _node.factory());
		assertEquals(123, (int) _node.value());
	}

	@Test
	public void testParseIntegerSpace() {
		final IntegerLiteralNode _node;
		_node = ((IntegerLiteralNode) Parser.factory.source_("123 ").parseExpression());
		assertEquals((org.gravel.support.jvm.SmalltalkFactory) IntegerLiteralNode.factory, (org.gravel.support.jvm.SmalltalkFactory) _node.factory());
		assertEquals(123, (int) _node.value());
	}

	@Test
	public void testParseKeywordBinaryUnaryExpression1() {
		final Statement _node;
		_node = Parser.factory.source_("2 bar + 7 foo: 7 bar: 4 baz foo: 2 + 1 boo: 3 foo + 2 roo: 3 + 2 foo noo: 3 hoo + 2 joo").parseExpression();
		assertTrue(org.gravel.support.jvm.ObjectExtensions.equals_(_node.factory(), KeywordMessageNode.factory));
		assertEquals((String) "2 bar + 7\n\tfoo: 7\n\tbar: 4 baz\n\tfoo: 2 + 1\n\tboo: 3 foo + 2\n\troo: 3 + 2 foo\n\tnoo: 3 hoo + 2 joo", (String) _node.prettySourceString());
	}

	@Test
	public void testParseKeywordBinaryUnaryExpression2() {
		final Statement _node;
		_node = Parser.factory.source_("2 bar foo: 7 bar: 4 baz foo: 2 + 1 boo: 3 foo + 2 roo: 3 + 2 foo noo: 3 hoo + 2 joo").parseExpression();
		assertTrue(org.gravel.support.jvm.ObjectExtensions.equals_(_node.factory(), KeywordMessageNode.factory));
		assertEquals((String) "2 bar\n\tfoo: 7\n\tbar: 4 baz\n\tfoo: 2 + 1\n\tboo: 3 foo + 2\n\troo: 3 + 2 foo\n\tnoo: 3 hoo + 2 joo", (String) _node.prettySourceString());
	}

	@Test
	public void testParseKeywordBinaryUnaryExpression3() {
		final Statement _node;
		_node = Parser.factory.source_("2 + 7 foo: 7 bar: 4 baz foo: 2 + 1 boo: 3 foo + 2 roo: 3 + 2 foo noo: 3 hoo + 2 joo").parseExpression();
		assertTrue(org.gravel.support.jvm.ObjectExtensions.equals_(_node.factory(), KeywordMessageNode.factory));
		assertEquals((String) "2 + 7\n\tfoo: 7\n\tbar: 4 baz\n\tfoo: 2 + 1\n\tboo: 3 foo + 2\n\troo: 3 + 2 foo\n\tnoo: 3 hoo + 2 joo", (String) _node.prettySourceString());
	}

	@Test
	public void testParseKeywordBinaryUnaryExpression4() {
		final Statement _node;
		_node = Parser.factory.source_("2 + 7 bar foo: 7 bar: 4 baz foo: 2 + 1 boo: 3 foo + 2 roo: 3 + 2 foo noo: 3 hoo + 2 joo").parseExpression();
		assertTrue(org.gravel.support.jvm.ObjectExtensions.equals_(_node.factory(), KeywordMessageNode.factory));
		assertEquals((String) "2 + 7 bar\n\tfoo: 7\n\tbar: 4 baz\n\tfoo: 2 + 1\n\tboo: 3 foo + 2\n\troo: 3 + 2 foo\n\tnoo: 3 hoo + 2 joo", (String) _node.prettySourceString());
	}

	@Test
	public void testParseKeywordExpression() {
		final Statement _node;
		_node = Parser.factory.source_(" 3 foo: 7 bar: 4 ").parseExpression();
		assertEquals((org.gravel.support.jvm.SmalltalkFactory) KeywordMessageNode.factory, (org.gravel.support.jvm.SmalltalkFactory) _node.factory());
		assertEquals((String) "3 foo: 7 bar: 4", (String) _node.prettySourceString());
	}

	@Test
	public void testParseKeywordMethod1() {
		final KeywordMethodNode _node;
		_node = ((KeywordMethodNode) Parser.factory.parseMethod_("foo: arg1 ^bar"));
		assertTrue(org.gravel.support.jvm.ObjectExtensions.equals_(_node.factory(), KeywordMethodNode.factory));
		assertEquals((String) "foo: arg1\n\t^bar", (String) _node.prettySourceString());
	}

	@Test
	public void testParseKeywordMethod2() {
		final KeywordMethodNode _node;
		_node = ((KeywordMethodNode) Parser.factory.parseMethod_("foo: arg1 bar: arg2 ^bar"));
		assertTrue(org.gravel.support.jvm.ObjectExtensions.equals_(_node.factory(), KeywordMethodNode.factory));
		assertEquals((String) "foo: arg1 bar: arg2\n\t^bar", (String) _node.prettySourceString());
	}

	@Test
	public void testParseLiteralArray() {
		final ArrayLiteralNode _node;
		_node = ((ArrayLiteralNode) Parser.factory.source_("#(#foo foo \'foo\' 1 (a b c) #( a b c) ((x)) () #[1 2 3])").parseExpression());
		assertTrue(org.gravel.support.jvm.ObjectExtensions.equals_(_node.factory(), ArrayLiteralNode.factory));
		assertEquals((String) "#(#foo #foo \'foo\' 1 #(#a #b #c) #(#a #b #c) #(#(#x)) #() #[1 2 3])", (String) _node.prettySourceString());
		assertTrue(org.gravel.support.jvm.IntegerExtensions.equals_(_node.value().length, 9));
	}

	@Test
	public void testParseMethodWithArgAndReturnType() {
		final BinaryMethodNode _node;
		_node = ((BinaryMethodNode) Parser.factory.parseMethod_("+ arg {String} {^String}^bar"));
		assertTrue(org.gravel.support.jvm.ObjectExtensions.equals_(_node.factory(), BinaryMethodNode.factory));
		assertEquals((String) "+ arg {String} {^String}\n\t^bar", (String) _node.prettySourceString());
		assertTrue(_node.argument().type() != null);
		assertTrue(_node.returnType() != null);
	}

	@Test
	public void testParseMethodWithArgType() {
		final BinaryMethodNode _node;
		_node = ((BinaryMethodNode) Parser.factory.parseMethod_("+ arg {String} ^bar"));
		assertTrue(org.gravel.support.jvm.ObjectExtensions.equals_(_node.factory(), BinaryMethodNode.factory));
		assertEquals((String) "+ arg {String}\n\t^bar", (String) _node.prettySourceString());
		assertTrue(_node.argument().type() != null);
		assertTrue(_node.returnType() == null);
	}

	@Test
	public void testParseMethodWithReturnType() {
		final BinaryMethodNode _node;
		_node = ((BinaryMethodNode) Parser.factory.parseMethod_("+ arg {^String} ^bar"));
		assertTrue(org.gravel.support.jvm.ObjectExtensions.equals_(_node.factory(), BinaryMethodNode.factory));
		assertEquals((String) "+ arg {^String}\n\t^bar", (String) _node.prettySourceString());
	}

	@Test
	public void testParseMethodWithReturnTypeWithSpace() {
		final BinaryMethodNode _node;
		_node = ((BinaryMethodNode) Parser.factory.parseMethod_("+ arg {^ String} ^bar"));
		assertTrue(org.gravel.support.jvm.ObjectExtensions.equals_(_node.factory(), BinaryMethodNode.factory));
		assertEquals((String) "+ arg {^String}\n\t^bar", (String) _node.prettySourceString());
	}

	@Test
	public void testParseNamespacedVariable() {
		final NamespacedVariableNode _node;
		_node = ((NamespacedVariableNode) Parser.factory.source_(" foo.bar.baz ").parseExpression());
		assertEquals((org.gravel.support.jvm.SmalltalkFactory) NamespacedVariableNode.factory, (org.gravel.support.jvm.SmalltalkFactory) _node.factory());
		assertEquals((String) "foo.bar.baz", (String) _node.prettySourceString());
		assertEquals((String[]) new String[] { "foo", "bar", "baz" }, (String[]) _node.path());
	}

	@Test
	public void testParseNegativeInteger() {
		final IntegerLiteralNode _node;
		_node = ((IntegerLiteralNode) Parser.factory.source_("-123").parseExpression());
		assertEquals((org.gravel.support.jvm.SmalltalkFactory) IntegerLiteralNode.factory, (org.gravel.support.jvm.SmalltalkFactory) _node.factory());
		assertEquals(-123, (int) _node.value());
	}

	@Test
	public void testParseNestedExpression() {
		final Statement _node;
		_node = Parser.factory.source_(" 3 + (4 + 5) ").parseExpression();
		assertTrue(org.gravel.support.jvm.ObjectExtensions.equals_(_node.factory(), BinaryMessageNode.factory));
		assertEquals((String) "3 + (4 + 5)", (String) _node.prettySourceString());
	}

	@Test
	public void testParseNilaryBlockNoTemps() {
		final Statement _node;
		_node = Parser.factory.source_("[1 foo. 2 bar]").parseExpression();
		assertTrue(org.gravel.support.jvm.ObjectExtensions.equals_(_node.factory(), BlockNode.factory));
		assertEquals((String) "\n[\n1 foo.\n2 bar]", (String) _node.prettySourceString());
	}

	@Test
	public void testParseNilaryBlockWithTemps() {
		final Statement _node;
		_node = Parser.factory.source_("[| a b | a foo. b bar]").parseExpression();
		assertTrue(org.gravel.support.jvm.ObjectExtensions.equals_(_node.factory(), BlockNode.factory));
		assertEquals((String) "\n[\n| a b |\na foo.\nb bar]", (String) _node.prettySourceString());
	}

	@Test
	public void testParseNilInArray1() {
		final ArrayLiteralNode _node;
		_node = ((ArrayLiteralNode) Parser.factory.source_("#(nil)").parseExpression());
		assertEquals((org.gravel.support.jvm.SmalltalkFactory) ArrayLiteralNode.factory, (org.gravel.support.jvm.SmalltalkFactory) _node.factory());
		assertEquals((Object) null, (Object) _node.value()[0]);
	}

	@Test
	public void testParseOrType() {
		final BinaryMethodNode _node;
		_node = ((BinaryMethodNode) Parser.factory.parseMethod_("+ arg {String | Nil} ^bar"));
		assertTrue(org.gravel.support.jvm.ObjectExtensions.equals_(_node.factory(), BinaryMethodNode.factory));
		assertEquals((String) "+ arg {String | Nil}\n\t^bar", (String) _node.prettySourceString());
	}

	@Test
	public void testParseReturn() {
		final Statement _node;
		_node = Parser.factory.source_("[:a | ^a]").parseExpression();
		assertTrue(org.gravel.support.jvm.ObjectExtensions.equals_(_node.factory(), BlockNode.factory));
		assertEquals((String) "[:a | ^a]", (String) _node.prettySourceString());
	}

	@Test
	public void testParseString1() {
		final StringLiteralNode _node;
		_node = ((StringLiteralNode) Parser.factory.source_("\'fromage\'").parseExpression());
		assertTrue(org.gravel.support.jvm.ObjectExtensions.equals_(_node.factory(), StringLiteralNode.factory));
		assertTrue(org.gravel.support.jvm.StringExtensions.equals_(_node.value(), "fromage"));
	}

	@Test
	public void testParseString2() {
		final StringLiteralNode _node;
		_node = ((StringLiteralNode) Parser.factory.source_("\'from\'\'age\'").parseExpression());
		assertTrue(org.gravel.support.jvm.ObjectExtensions.equals_(_node.factory(), StringLiteralNode.factory));
		assertTrue(org.gravel.support.jvm.StringExtensions.equals_(_node.value(), "from\'age"));
	}

	@Test
	public void testParseSymbol1() {
		final SymbolLiteralNode _node;
		_node = ((SymbolLiteralNode) Parser.factory.source_("#\'from\'\'age\'").parseExpression());
		assertTrue(org.gravel.support.jvm.ObjectExtensions.equals_(_node.factory(), SymbolLiteralNode.factory));
		assertTrue(org.gravel.support.jvm.ObjectExtensions.equals_(_node.value(), org.gravel.core.Symbol.value("from\'age")));
	}

	@Test
	public void testParseSymbol2() {
		final SymbolLiteralNode _node;
		_node = ((SymbolLiteralNode) Parser.factory.source_("#foo").parseExpression());
		assertTrue(org.gravel.support.jvm.ObjectExtensions.equals_(_node.factory(), SymbolLiteralNode.factory));
		assertTrue(org.gravel.support.jvm.ObjectExtensions.equals_(_node.value(), org.gravel.core.Symbol.value("foo")));
	}

	@Test
	public void testParseUnaryBlockNoTemps() {
		final Statement _node;
		_node = Parser.factory.source_("[:a | a foo. 2 bar]").parseExpression();
		assertTrue(org.gravel.support.jvm.ObjectExtensions.equals_(_node.factory(), BlockNode.factory));
		assertEquals((String) "\n[:a | \na foo.\n2 bar]", (String) _node.prettySourceString());
	}

	@Test
	public void testParseUnaryBlockWithTemps() {
		final Statement _node;
		_node = Parser.factory.source_("[:a | | b | a foo. b bar]").parseExpression();
		assertTrue(org.gravel.support.jvm.ObjectExtensions.equals_(_node.factory(), BlockNode.factory));
		assertEquals((String) "\n[:a | \n| b |\na foo.\nb bar]", (String) _node.prettySourceString());
	}

	@Test
	public void testParseUnaryExpression() {
		final UnaryMessageNode _node;
		_node = ((UnaryMessageNode) Parser.factory.source_(" 3 foo ").parseExpression());
		assertTrue(org.gravel.support.jvm.ObjectExtensions.equals_(_node.factory(), UnaryMessageNode.factory));
		assertEquals((String) "3 foo", (String) _node.prettySourceString());
	}

	@Test
	public void testParseUnaryMethod() {
		final UnaryMethodNode _node;
		_node = ((UnaryMethodNode) Parser.factory.parseMethod_("foo self baz. ^bar"));
		assertTrue(org.gravel.support.jvm.ObjectExtensions.equals_(_node.factory(), UnaryMethodNode.factory));
		assertEquals((String) "foo\n\tself baz.\n\t^bar", (String) _node.prettySourceString());
	}

	@Test
	public void testParseVariable() {
		final VariableNode _node;
		_node = ((VariableNode) Parser.factory.source_(" foo ").parseExpression());
		assertTrue(org.gravel.support.jvm.ObjectExtensions.equals_(_node.factory(), VariableNode.factory));
		assertEquals((String) "foo", (String) _node.prettySourceString());
	}

	@Test
	public void testParseVariableDot() {
		final BlockNode _node;
		_node = ((BlockNode) Parser.factory.source_(" [foo. bar] ").parseExpression());
		assertTrue(org.gravel.support.jvm.ObjectExtensions.equals_(_node.factory(), BlockNode.factory));
		assertEquals((String) "\n[\nfoo.\nbar]", (String) _node.prettySourceString());
	}
}
