(reader defineClass: 'MethodMirror' superclass: 'st.gravel.lang.Mirror')
!
(reader propertyAt: 'javaClass' put: 'st.gravel.support.jvm.MethodMirror')
!
(reader addMethod: '')
!
mclass
	<primitive: 'mclass'>
	
!
(reader addMethod: '')
!
packageName
	<primitive: 'packageName'>
	
!
(reader addMethod: '')
!
protocol
	<primitive: 'protocol'>
	
!
(reader addMethod: '')
!
selector
	<primitive: 'selector'>
	
!
(reader addMethod: '')
!
source
	<primitive: 'source'>
	
!
