(reader extendTrait: 'String')
!
(reader addSimpleTrait: 'st.gravel.lang.collections.interface.Collection')
!
(reader addSimpleTrait: 'st.gravel.lang.collections.interface.SequencedReadable')
!
(reader addSimpleTrait: 'st.gravel.lang.Comparable')
!
(reader addSimpleClassTrait: 'st.gravel.lang.collections.interface.Collection class')
!
(reader addSimpleClassTrait: 'st.gravel.lang.collections.interface.SequencedReadable class')
!
(reader addSimpleClassTrait: 'st.gravel.lang.Comparable class')
!
(reader addMethod: 'As yet unclassified')
!
sunitMatch: aString
	^self match: aString
!
