(reader extendTrait: 'Symbol')
!
(reader addSimpleTrait: 'st.gravel.lang.collections.interface.String')
!
(reader addSimpleClassTrait: 'st.gravel.lang.collections.interface.String class')
!
(reader addInstVar: '____str_Gravel_st_gravel_lang_collections_interface_String__Gravel_st_gravel_lang_collections_interface_Symbol___')
!
(reader addMethod: 'As yet unclassified')
!
asSymbol
	^self
!
(reader addMethod: 'As yet unclassified')
!
sunitAsSymbol
	^self asSymbol
!
