package st.gravel.support.compiler.ast;

/*
	This file is automatically generated from typed smalltalk source. Do not edit by hand.
	(C) AG5.com
*/

import java.math.BigInteger;
import st.gravel.support.jvm.NonLocalReturn;
import st.gravel.support.compiler.ast.TypeNode;
import st.gravel.support.compiler.ast.TypeNode.TypeNode_Factory;
import st.gravel.support.compiler.ast.NodeVisitor;
import st.gravel.support.compiler.ast.Node;
import st.gravel.support.compiler.ast.SourcePrinter;
import st.gravel.support.compiler.ast.SourcePosition;

public class ClassTypeNode extends TypeNode implements Cloneable {

	public static ClassTypeNode_Factory factory = new ClassTypeNode_Factory();

	TypeNode _node;

	public static class ClassTypeNode_Factory extends TypeNode_Factory {

		public ClassTypeNode basicNew() {
			ClassTypeNode newInstance = new ClassTypeNode();
			newInstance.initialize();
			return newInstance;
		}

		public ClassTypeNode node_(final TypeNode _aTypeVariableNode) {
			return ((ClassTypeNode) this.basicNew().initializeNode_(_aTypeVariableNode));
		}
	}

	static public ClassTypeNode _node_(Object receiver, final TypeNode _aTypeVariableNode) {
		return factory.node_(_aTypeVariableNode);
	}

	@Override
	public <X> X accept_(final NodeVisitor<X> _visitor) {
		return _visitor.visitClassTypeNode_(this);
	}

	@Override
	public ClassTypeNode allNodesDo_(final st.gravel.support.jvm.Block1<Object, Node> _aBlock) {
		this.nodesDo_(new st.gravel.support.jvm.Block1<Object, Node>() {

			@Override
			public Object value_(final Node _each) {
				return _each.withAllNodesDo_(_aBlock);
			}
		});
		return this;
	}

	@Override
	public ClassTypeNode allNodesDo_pruneWhere_(final st.gravel.support.jvm.Block1<Object, Node> _aBlock, final st.gravel.support.jvm.Block1<Boolean, Node> _pruneBlock) {
		this.nodesDo_(new st.gravel.support.jvm.Block1<Object, Node>() {

			@Override
			public Object value_(final Node _each) {
				if (!_pruneBlock.value_(_each)) {
					return _each.withAllNodesDo_pruneWhere_(_aBlock, _pruneBlock);
				}
				return ClassTypeNode.this;
			}
		});
		return this;
	}

	public ClassTypeNode copy() {
		try {
			ClassTypeNode _temp1 = (ClassTypeNode) this.clone();
			_temp1.postCopy();
			return _temp1;
		} catch (CloneNotSupportedException e) {
			throw new RuntimeException(e);
		}
	}

	@Override
	public boolean equals(final Object _anObject) {
		if (!super.equals(_anObject)) {
			return false;
		}
		if (this._node == null) {
			if (!(((ClassTypeNode) _anObject)._node == null)) {
				return false;
			}
		} else {
			if (!st.gravel.support.jvm.ObjectExtensions.equals_(this._node, ((ClassTypeNode) _anObject)._node)) {
				return false;
			}
		}
		return true;
	}

	public ClassTypeNode_Factory factory() {
		return factory;
	}

	@Override
	public int hashCode() {
		return (super.hashCode() ^ (_node == null ? 0 : _node.hashCode()));
	}

	public ClassTypeNode initializeNode_(final TypeNode _aTypeVariableNode) {
		_node = _aTypeVariableNode;
		this.initialize();
		return this;
	}

	@Override
	public ClassTypeNode innerSourceOn_(final StringBuilder _aStream) {
		_node.innerSourceOn_(_aStream);
		_aStream.append(" class");
		return this;
	}

	public TypeNode instanceType() {
		return _node;
	}

	@Override
	public boolean isNilType() {
		return false;
	}

	@Override
	public ClassTypeNode localVarNamesDo_(final st.gravel.support.jvm.Block1<Object, String> _aBlock) {
		return this;
	}

	public TypeNode node() {
		return _node;
	}

	@Override
	public ClassTypeNode prettySourceOn_(final StringBuilder _aStream) {
		SourcePrinter.factory.on_(_aStream).visit_(this);
		return this;
	}

	@Override
	public ClassTypeNode printOn_(final StringBuilder _aStream) {
		final String _title;
		_title = this.factory().toString();
		_aStream.append(st.gravel.support.jvm.CharacterExtensions.isVowel(_title.charAt(0)) ? "an " : "a ");
		_aStream.append(_title);
		_aStream.append('[');
		this.sourceOn_(_aStream);
		_aStream.append(']');
		return this;
	}

	@Override
	public ClassTypeNode pvtSetSourcePosition_(final SourcePosition _aSourcePosition) {
		_sourcePosition = _aSourcePosition;
		return this;
	}

	@Override
	public boolean referencesSelfOrInstanceType() {
		return _node.referencesSelfOrInstanceType();
	}

	@Override
	public ClassTypeNode sourceOn_(final StringBuilder _aStream) {
		this.innerSourceOn_(_aStream);
		return this;
	}

	@Override
	public ClassTypeNode typeDefsDo_(final st.gravel.support.jvm.Block1<Object, TypeNode> _aBlock) {
		return this;
	}

	@Override
	public ClassTypeNode withAllNodesDo_(final st.gravel.support.jvm.Block1<Object, Node> _aBlock) {
		_aBlock.value_(this);
		this.allNodesDo_(_aBlock);
		return this;
	}

	@Override
	public ClassTypeNode withAllNodesDo_pruneWhere_(final st.gravel.support.jvm.Block1<Object, Node> _aBlock, final st.gravel.support.jvm.Block1<Boolean, Node> _pruneBlock) {
		_aBlock.value_(this);
		this.allNodesDo_pruneWhere_(_aBlock, _pruneBlock);
		return this;
	}

	@Override
	public ClassTypeNode withSourcePosition_(final SourcePosition _aSourcePosition) {
		if (_sourcePosition == _aSourcePosition) {
			return ClassTypeNode.this;
		}
		return this.copy().pvtSetSourcePosition_(_aSourcePosition);
	}
}
