package st.gravel.support.compiler.ast;

/*
	This file is automatically generated from typed smalltalk source. Do not edit by hand.
	(C) AG5.com
*/

import java.math.BigInteger;
import st.gravel.support.jvm.NonLocalReturn;
import st.gravel.support.compiler.ast.AbstractTraitUsageToDirectiveConverter;
import st.gravel.support.compiler.ast.AbstractTraitUsageToDirectiveConverter.AbstractTraitUsageToDirectiveConverter_Factory;
import st.gravel.support.compiler.ast.SimpleTraitUsageNode;
import st.gravel.support.compiler.ast.Node;
import st.gravel.support.compiler.ast.StringLiteralNode;

public class ClassTraitUsageToDirectiveConverter extends AbstractTraitUsageToDirectiveConverter implements Cloneable {

	public static ClassTraitUsageToDirectiveConverter_Factory factory = new ClassTraitUsageToDirectiveConverter_Factory();

	public static class ClassTraitUsageToDirectiveConverter_Factory extends AbstractTraitUsageToDirectiveConverter_Factory {

		public ClassTraitUsageToDirectiveConverter basicNew() {
			ClassTraitUsageToDirectiveConverter newInstance = new ClassTraitUsageToDirectiveConverter();
			newInstance.initialize();
			return newInstance;
		}
	}

	public ClassTraitUsageToDirectiveConverter copy() {
		try {
			ClassTraitUsageToDirectiveConverter _temp1 = (ClassTraitUsageToDirectiveConverter) this.clone();
			_temp1.postCopy();
			return _temp1;
		} catch (CloneNotSupportedException e) {
			throw new RuntimeException(e);
		}
	}

	public ClassTraitUsageToDirectiveConverter_Factory factory() {
		return factory;
	}

	@Override
	public Node[] produceSimpleNoMethod_(final SimpleTraitUsageNode _aSimpleTraitUsageNode) {
		return st.gravel.support.jvm.ArrayFactory.with_(this.reader().send_with_("addSimpleClassTrait:", StringLiteralNode.factory.value_(_aSimpleTraitUsageNode.reference().toString())));
	}
}
