package st.gravel.support.compiler.ast;

/*
	This file is automatically generated from typed smalltalk source. Do not edit by hand.
	(C) AG5.com
*/

import java.math.BigInteger;
import st.gravel.support.jvm.NonLocalReturn;
import st.gravel.support.compiler.ast.StateAccessNode;
import st.gravel.support.compiler.ast.StateAccessNode.StateAccessNode_Factory;
import st.gravel.support.compiler.ast.Expression;
import st.gravel.support.compiler.ast.NodeVisitor;
import st.gravel.support.compiler.ast.Node;
import st.gravel.support.compiler.ast.AssignmentNode;
import st.gravel.support.compiler.ast.VariableNode;
import st.gravel.support.compiler.ast.SourcePrinter;
import st.gravel.support.compiler.ast.SourcePosition;

public class WriteHolderNode extends StateAccessNode implements Cloneable {

	public static WriteHolderNode_Factory factory = new WriteHolderNode_Factory();

	Expression _value;

	String _varName;

	public static class WriteHolderNode_Factory extends StateAccessNode_Factory {

		public WriteHolderNode basicNew() {
			WriteHolderNode newInstance = new WriteHolderNode();
			newInstance.initialize();
			return newInstance;
		}

		public WriteHolderNode varName_value_(final String _aString, final Expression _anIntegerLiteralNode) {
			return ((WriteHolderNode) this.basicNew().initializeVarName_value_(_aString, _anIntegerLiteralNode));
		}
	}

	static public WriteHolderNode _varName_value_(Object receiver, final String _aString, final Expression _anIntegerLiteralNode) {
		return factory.varName_value_(_aString, _anIntegerLiteralNode);
	}

	@Override
	public <X> X accept_(final NodeVisitor<X> _visitor) {
		return _visitor.visitWriteHolderNode_(this);
	}

	@Override
	public WriteHolderNode allNodesDo_(final st.gravel.support.jvm.Block1<Object, Node> _aBlock) {
		this.nodesDo_(new st.gravel.support.jvm.Block1<Object, Node>() {

			@Override
			public Object value_(final Node _each) {
				return _each.withAllNodesDo_(_aBlock);
			}
		});
		return this;
	}

	@Override
	public WriteHolderNode allNodesDo_pruneWhere_(final st.gravel.support.jvm.Block1<Object, Node> _aBlock, final st.gravel.support.jvm.Block1<Boolean, Node> _pruneBlock) {
		this.nodesDo_(new st.gravel.support.jvm.Block1<Object, Node>() {

			@Override
			public Object value_(final Node _each) {
				if (!_pruneBlock.value_(_each)) {
					return _each.withAllNodesDo_pruneWhere_(_aBlock, _pruneBlock);
				}
				return WriteHolderNode.this;
			}
		});
		return this;
	}

	public WriteHolderNode copy() {
		try {
			WriteHolderNode _temp1 = (WriteHolderNode) this.clone();
			_temp1.postCopy();
			return _temp1;
		} catch (CloneNotSupportedException e) {
			throw new RuntimeException(e);
		}
	}

	@Override
	public boolean equals(final Object _anObject) {
		if (!super.equals(_anObject)) {
			return false;
		}
		if (this._varName == null) {
			if (!(((WriteHolderNode) _anObject)._varName == null)) {
				return false;
			}
		} else {
			if (!st.gravel.support.jvm.StringExtensions.equals_(this._varName, ((WriteHolderNode) _anObject)._varName)) {
				return false;
			}
		}
		if (this._value == null) {
			if (!(((WriteHolderNode) _anObject)._value == null)) {
				return false;
			}
		} else {
			if (!st.gravel.support.jvm.ObjectExtensions.equals_(this._value, ((WriteHolderNode) _anObject)._value)) {
				return false;
			}
		}
		return true;
	}

	public WriteHolderNode_Factory factory() {
		return factory;
	}

	@Override
	public int hashCode() {
		return ((super.hashCode() ^ _varName.hashCode()) ^ (_value == null ? 0 : _value.hashCode()));
	}

	public WriteHolderNode initializeVarName_value_(final String _aString, final Expression _anIntegerLiteralNode) {
		_varName = _aString;
		_value = _anIntegerLiteralNode;
		this.initialize();
		return this;
	}

	@Override
	public WriteHolderNode innerSourceOn_(final StringBuilder _aStream) {
		_aStream.append("{");
		_aStream.append(_varName);
		_aStream.append(" value: ");
		_value.sourceOn_(_aStream);
		_aStream.append("}");
		return this;
	}

	@Override
	public WriteHolderNode localVarNamesDo_(final st.gravel.support.jvm.Block1<Object, String> _aBlock) {
		_aBlock.value_(_varName);
		return this;
	}

	@Override
	public String name() {
		return _varName;
	}

	@Override
	public WriteHolderNode nodesDo_(final st.gravel.support.jvm.Block1<Object, Node> _aBlock) {
		_aBlock.value_(_value);
		return this;
	}

	@Override
	public WriteHolderNode prettySourceOn_(final StringBuilder _aStream) {
		SourcePrinter.factory.on_(_aStream).visit_(this);
		return this;
	}

	@Override
	public WriteHolderNode printOn_(final StringBuilder _aStream) {
		final String _title;
		_title = this.factory().toString();
		_aStream.append(st.gravel.support.jvm.CharacterExtensions.isVowel(_title.charAt(0)) ? "an " : "a ");
		_aStream.append(_title);
		_aStream.append('[');
		this.sourceOn_(_aStream);
		_aStream.append(']');
		return this;
	}

	@Override
	public WriteHolderNode pvtSetSourcePosition_(final SourcePosition _aSourcePosition) {
		_sourcePosition = _aSourcePosition;
		return this;
	}

	@Override
	public boolean referencesVariable_(final String _aString) {
		return st.gravel.support.jvm.StringExtensions.equals_(_varName, _aString);
	}

	@Override
	public WriteHolderNode sourceOn_(final StringBuilder _aStream) {
		_aStream.append(st.gravel.core.Symbol.value(this.getClass().getSimpleName()));
		_aStream.append(' ');
		this.innerSourceOn_(_aStream);
		return this;
	}

	@Override
	public Expression unoptimized() {
		return AssignmentNode.factory.variable_value_(VariableNode.factory.name_(this.name()), _value);
	}

	public Expression value() {
		return _value;
	}

	public String varName() {
		return _varName;
	}

	@Override
	public WriteHolderNode withAllNodesDo_(final st.gravel.support.jvm.Block1<Object, Node> _aBlock) {
		_aBlock.value_(this);
		this.allNodesDo_(_aBlock);
		return this;
	}

	@Override
	public WriteHolderNode withAllNodesDo_pruneWhere_(final st.gravel.support.jvm.Block1<Object, Node> _aBlock, final st.gravel.support.jvm.Block1<Boolean, Node> _pruneBlock) {
		_aBlock.value_(this);
		this.allNodesDo_pruneWhere_(_aBlock, _pruneBlock);
		return this;
	}

	@Override
	public WriteHolderNode withSourcePosition_(final SourcePosition _aSourcePosition) {
		if (_sourcePosition == _aSourcePosition) {
			return WriteHolderNode.this;
		}
		return this.copy().pvtSetSourcePosition_(_aSourcePosition);
	}
}
