(reader defineClass: 'PackageMirror' superclass: 'org.gravel.lang.Mirror')
!
(reader propertyAt: 'javaClass' put: 'org.gravel.support.jvm.PackageMirror')
!
(reader addMethod: 'As yet unclassified')
!
definedClasses
	<primitive: 'definedClasses'>
	
!
(reader addMethod: 'As yet unclassified')
!
definedTraits
	<primitive: 'definedTraits'>
	
!
(reader addMethod: 'gravel')
!
name
	<primitive: 'name'>
	
!
